services:
  filebrowser:
    volumes:
      - './data/folder:/srv'
      - './data/database:/home/filebrowser/database'
      - './app-resource/config/config.yaml:/home/filebrowser/config.yaml'
    ports:
      - '9080:80'
    image: gtstef/filebrowser
